# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/spot_cam/version.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/spot_cam/version.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import header_pb2 as bosdyn_dot_api_dot_header__pb2
from bosdyn.api import robot_id_pb2 as bosdyn_dot_api_dot_robot__id__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!bosdyn/api/spot_cam/version.proto\x12\x13\x62osdyn.api.spot_cam\x1a\x17\x62osdyn/api/header.proto\x1a\x19\x62osdyn/api/robot_id.proto\"F\n\x19GetSoftwareVersionRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\"\x86\x01\n\x1aGetSoftwareVersionResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12,\n\x07version\x18\x02 \x01(\x0b\x32\x1b.bosdyn.api.SoftwareVersion\x12\x0e\n\x06\x64\x65tail\x18\x03 \x01(\tB+B\x0cVersionProtoZ\x1b\x62osdyn/api/spot_cam/versionb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.spot_cam.version_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\014VersionProtoZ\033bosdyn/api/spot_cam/version'
  _globals['_GETSOFTWAREVERSIONREQUEST']._serialized_start=110
  _globals['_GETSOFTWAREVERSIONREQUEST']._serialized_end=180
  _globals['_GETSOFTWAREVERSIONRESPONSE']._serialized_start=183
  _globals['_GETSOFTWAREVERSIONRESPONSE']._serialized_end=317
# @@protoc_insertion_point(module_scope)
