# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/spot_cam/camera.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/spot_cam/camera.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import geometry_pb2 as bosdyn_dot_api_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n bosdyn/api/spot_cam/camera.proto\x12\x13\x62osdyn.api.spot_cam\x1a\x19\x62osdyn/api/geometry.proto\"\xbe\x04\n\x06\x43\x61mera\x12\x0c\n\x04name\x18\x01 \x01(\t\x12$\n\nresolution\x18\x02 \x01(\x0b\x32\x10.bosdyn.api.Vec2\x12\x17\n\x0f\x62\x61se_frame_name\x18\x03 \x01(\t\x12\x32\n\x11\x62\x61se_tfrom_sensor\x18\x04 \x01(\x0b\x32\x13.bosdyn.api.SE3PoseB\x02\x18\x01\x12.\n\x11\x62\x61se_tform_sensor\x18\x07 \x01(\x0b\x32\x13.bosdyn.api.SE3Pose\x12@\n\x07pinhole\x18\x05 \x01(\x0b\x32-.bosdyn.api.spot_cam.Camera.PinholeIntrinsicsH\x00\x12@\n\tspherical\x18\x06 \x01(\x0b\x32+.bosdyn.api.spot_cam.Camera.SphericalLimitsH\x00\x1a\x93\x01\n\x11PinholeIntrinsics\x12&\n\x0c\x66ocal_length\x18\x01 \x01(\x0b\x32\x10.bosdyn.api.Vec2\x12&\n\x0c\x63\x65nter_point\x18\x02 \x01(\x0b\x32\x10.bosdyn.api.Vec2\x12\n\n\x02k1\x18\x03 \x01(\x02\x12\n\n\x02k2\x18\x04 \x01(\x02\x12\n\n\x02k3\x18\x05 \x01(\x02\x12\n\n\x02k4\x18\x06 \x01(\x02\x1a[\n\x0fSphericalLimits\x12#\n\tmin_angle\x18\x01 \x01(\x0b\x32\x10.bosdyn.api.Vec2\x12#\n\tmax_angle\x18\x02 \x01(\x0b\x32\x10.bosdyn.api.Vec2B\x0c\n\nintrinsicsB)B\x0b\x43\x61meraProtoZ\x1a\x62osdyn/api/spot_cam/camerab\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.spot_cam.camera_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\013CameraProtoZ\032bosdyn/api/spot_cam/camera'
  _globals['_CAMERA'].fields_by_name['base_tfrom_sensor']._loaded_options = None
  _globals['_CAMERA'].fields_by_name['base_tfrom_sensor']._serialized_options = b'\030\001'
  _globals['_CAMERA']._serialized_start=85
  _globals['_CAMERA']._serialized_end=659
  _globals['_CAMERA_PINHOLEINTRINSICS']._serialized_start=405
  _globals['_CAMERA_PINHOLEINTRINSICS']._serialized_end=552
  _globals['_CAMERA_SPHERICALLIMITS']._serialized_start=554
  _globals['_CAMERA_SPHERICALLIMITS']._serialized_end=645
# @@protoc_insertion_point(module_scope)
