# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/spot_cam/LED.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/spot_cam/LED.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import header_pb2 as bosdyn_dot_api_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x62osdyn/api/spot_cam/LED.proto\x12\x13\x62osdyn.api.spot_cam\x1a\x17\x62osdyn/api/header.proto\"D\n\x17GetLEDBrightnessRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\"\\\n\x18GetLEDBrightnessResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12\x14\n\x0c\x62rightnesses\x18\x02 \x03(\x02\"\xcf\x01\n\x17SetLEDBrightnessRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12T\n\x0c\x62rightnesses\x18\x02 \x03(\x0b\x32>.bosdyn.api.spot_cam.SetLEDBrightnessRequest.BrightnessesEntry\x1a\x33\n\x11\x42rightnessesEntry\x12\x0b\n\x03key\x18\x01 \x01(\x05\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\"F\n\x18SetLEDBrightnessResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeaderB(B\rLightingProtoZ\x17\x62osdyn/api/spot_cam/LEDb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.spot_cam.LED_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\rLightingProtoZ\027bosdyn/api/spot_cam/LED'
  _globals['_SETLEDBRIGHTNESSREQUEST_BRIGHTNESSESENTRY']._loaded_options = None
  _globals['_SETLEDBRIGHTNESSREQUEST_BRIGHTNESSESENTRY']._serialized_options = b'8\001'
  _globals['_GETLEDBRIGHTNESSREQUEST']._serialized_start=79
  _globals['_GETLEDBRIGHTNESSREQUEST']._serialized_end=147
  _globals['_GETLEDBRIGHTNESSRESPONSE']._serialized_start=149
  _globals['_GETLEDBRIGHTNESSRESPONSE']._serialized_end=241
  _globals['_SETLEDBRIGHTNESSREQUEST']._serialized_start=244
  _globals['_SETLEDBRIGHTNESSREQUEST']._serialized_end=451
  _globals['_SETLEDBRIGHTNESSREQUEST_BRIGHTNESSESENTRY']._serialized_start=400
  _globals['_SETLEDBRIGHTNESSREQUEST_BRIGHTNESSESENTRY']._serialized_end=451
  _globals['_SETLEDBRIGHTNESSRESPONSE']._serialized_start=453
  _globals['_SETLEDBRIGHTNESSRESPONSE']._serialized_end=523
# @@protoc_insertion_point(module_scope)
