openapi: 3.1.1
info:
  title: Robot Management API
  version: 1.0.0
  description: API to manage active robots, actions, and points of interest (POIs).

servers:
  - url: https://api.example.com
    description: Production server

tags:
  - name: robots
    description: Operations related to robot management
  - name: actions
    description: Operations related to robot actions
  - name: pois
    description: Operations related to points of interest (POIs)

paths:
  /robots:
    get:
      tags:
        - robots
      summary: Retrieve all active robots
      responses:
        '200':
          description: List of robots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RobotInfoDTO'
    post:
      tags:
        - robots
      summary: Add a new robot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RobotCreateDTO'
      responses:
        '201':
          description: Robot created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RobotIdDTO'

  /robots/{robotId}:
    parameters:
      - name: robotId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    get:
      tags:
        - robots
      summary: Retrieve information about a robot
      responses:
        '200':
          description: Robot details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RobotStatusDTO'
        '404':
          description: Robot not found
    delete:
      tags:
        - robots
      summary: Remove a robot
      responses:
        '204':
          description: Robot deleted

  /robots/{robotId}/actions:
    parameters:
      - name: robotId
        in: path
        required: true
        schema:
          type: string
          format: uuid
    post:
      tags:
        - actions
      summary: Create a new action for a robot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ActionCreate'
      responses:
        '201':
          description: Action created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Action'

  /pois:
    get:
      tags:
        - pois
      summary: Retrieve all POIs in the system
      responses:
        '200':
          description: List of POIs
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Poi'
    post:
      tags:
        - pois
      summary: Add a new POI
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PoiCreate'
      responses:
        '201':
          description: POI created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Poi'
    delete:
      tags:
        - pois
      summary: Delete a POI
      responses:
        '204':
          description: POI deleted

components:
  schemas:
    RobotInfoDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [MIR, SPOT]
        canonicalName:
          type: string
      required: [id, type, canonicalName]

    RobotIdDTO:
        type: object
        properties:
          id:
            type: string
            format: uuid
        required: [id]

    RobotStatusDTO:
      type: object
      properties:
        id:
          type: string
          format: uuid
        canonicalName:
          type: string
        state:
          type: string
          enum: [IDLE, ON_MISSION, RECHARGING]
        batteryLevel:
          type: number
          format: float
        currentPosition:
          type: object
          properties:
            x:
              type: number
              format: float
            y:
              type: number
              format: float
        type:
          type: string
          enum: [MIR, SPOT]
      required: [id, type, canonicalName, status]

    RobotCreateDTO:
      type: object
      required: [canonicalName]
      properties:
        canonicalName:
          type: string
      oneOf:
        - required: [type, host, username, password]
          properties:
            type:
              const: SPOT
            host:
              type: string
            username:
              type: string
            password:
              type: string
        - required: [type, host, apiToken]
          properties:
            type:
              const: MIR
            host:
              type: string
            apiToken:
              type: string

    Action:
      type: object
      properties:
        id:
          type: string
          format: uuid
        robotId:
          type: string
          format: uuid
        command:
          type: string
        timestamp:
          type: string
          format: date-time
      required: [id, robotId, command, timestamp]

    ActionCreate:
      type: object
      properties:
        command:
          type: string
      required: [command]

    Poi:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        lat:
          type: number
          format: float
        lon:
          type: number
          format: float
      required: [id, name, lat, lon]

    PoiCreate:
      type: object
      properties:
        name:
          type: string
        lat:
          type: number
          format: float
        lon:
          type: number
          format: float
      required: [name, lat, lon]

    PoiKey:
      type: object
      properties:
        id:
          type: string
          format: uuid
      required: [id]
