# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/gps/aggregator_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/gps/aggregator_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api.gps import aggregator_pb2 as bosdyn_dot_api_dot_gps_dot_aggregator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'bosdyn/api/gps/aggregator_service.proto\x12\x0e\x62osdyn.api.gps\x1a\x1f\x62osdyn/api/gps/aggregator.proto2j\n\x11\x41ggregatorService\x12U\n\nNewGpsData\x12!.bosdyn.api.gps.NewGpsDataRequest\x1a\".bosdyn.api.gps.NewGpsDataResponse\"\x00\x42\x18\x42\x16\x41ggregatorServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.gps.aggregator_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\026AggregatorServiceProto'
  _globals['_AGGREGATORSERVICE']._serialized_start=92
  _globals['_AGGREGATORSERVICE']._serialized_end=198
# @@protoc_insertion_point(module_scope)
