# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/data_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/data_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import data_index_pb2 as bosdyn_dot_api_dot_data__index__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x62osdyn/api/data_service.proto\x12\nbosdyn.api\x1a\x1b\x62osdyn/api/data_index.proto2\xe3\x03\n\x0b\x44\x61taService\x12S\n\x0cGetDataIndex\x12\x1f.bosdyn.api.GetDataIndexRequest\x1a .bosdyn.api.GetDataIndexResponse\"\x00\x12\x62\n\x11GetEventsComments\x12$.bosdyn.api.GetEventsCommentsRequest\x1a%.bosdyn.api.GetEventsCommentsResponse\"\x00\x12h\n\x13GetDataBufferStatus\x12&.bosdyn.api.GetDataBufferStatusRequest\x1a\'.bosdyn.api.GetDataBufferStatusResponse\"\x00\x12S\n\x0cGetDataPages\x12\x1f.bosdyn.api.GetDataPagesRequest\x1a .bosdyn.api.GetDataPagesResponse\"\x00\x12\\\n\x0f\x44\x65leteDataPages\x12\".bosdyn.api.DeleteDataPagesRequest\x1a#.bosdyn.api.DeleteDataPagesResponse\"\x00\x42\x12\x42\x10\x44\x61taServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.data_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\020DataServiceProto'
  _globals['_DATASERVICE']._serialized_start=75
  _globals['_DATASERVICE']._serialized_end=558
# @@protoc_insertion_point(module_scope)
