# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/directory.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/directory.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import header_pb2 as bosdyn_dot_api_dot_header__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x62osdyn/api/directory.proto\x12\nbosdyn.api\x1a\x17\x62osdyn/api/header.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfa\x01\n\x0cServiceEntry\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0e\n\x04type\x18\x02 \x01(\tH\x00\x12\x11\n\tauthority\x18\x03 \x01(\t\x12/\n\x0blast_update\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1b\n\x13user_token_required\x18\x05 \x01(\x08\x12\x1b\n\x13permission_required\x18\x07 \x01(\t\x12\x1d\n\x15liveness_timeout_secs\x18\x08 \x01(\x01\x12\x19\n\x11host_payload_guid\x18\t \x01(\tB\x0e\n\x0cservice_typeJ\x04\x08\x06\x10\x07\")\n\x08\x45ndpoint\x12\x0f\n\x07host_ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"Y\n\x16GetServiceEntryRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\"\xff\x01\n\x17GetServiceEntryResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12:\n\x06status\x18\x02 \x01(\x0e\x32*.bosdyn.api.GetServiceEntryResponse.Status\x12/\n\rservice_entry\x18\x03 \x01(\x0b\x32\x18.bosdyn.api.ServiceEntry\"K\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x1e\n\x1aSTATUS_NONEXISTENT_SERVICE\x10\x02\"F\n\x19ListServiceEntriesRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\"{\n\x1aListServiceEntriesResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12\x31\n\x0fservice_entries\x18\x02 \x03(\x0b\x32\x18.bosdyn.api.ServiceEntryB\x10\x42\x0e\x44irectoryProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.directory_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\016DirectoryProto'
  _globals['_SERVICEENTRY']._serialized_start=101
  _globals['_SERVICEENTRY']._serialized_end=351
  _globals['_ENDPOINT']._serialized_start=353
  _globals['_ENDPOINT']._serialized_end=394
  _globals['_GETSERVICEENTRYREQUEST']._serialized_start=396
  _globals['_GETSERVICEENTRYREQUEST']._serialized_end=485
  _globals['_GETSERVICEENTRYRESPONSE']._serialized_start=488
  _globals['_GETSERVICEENTRYRESPONSE']._serialized_end=743
  _globals['_GETSERVICEENTRYRESPONSE_STATUS']._serialized_start=668
  _globals['_GETSERVICEENTRYRESPONSE_STATUS']._serialized_end=743
  _globals['_LISTSERVICEENTRIESREQUEST']._serialized_start=745
  _globals['_LISTSERVICEENTRIESREQUEST']._serialized_end=815
  _globals['_LISTSERVICEENTRIESRESPONSE']._serialized_start=817
  _globals['_LISTSERVICEENTRIESRESPONSE']._serialized_end=940
# @@protoc_insertion_point(module_scope)
