# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/fault_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/fault_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import service_fault_pb2 as bosdyn_dot_api_dot_service__fault__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62osdyn/api/fault_service.proto\x12\nbosdyn.api\x1a\x1e\x62osdyn/api/service_fault.proto2\xdc\x01\n\x0c\x46\x61ultService\x12h\n\x13TriggerServiceFault\x12&.bosdyn.api.TriggerServiceFaultRequest\x1a\'.bosdyn.api.TriggerServiceFaultResponse\"\x00\x12\x62\n\x11\x43learServiceFault\x12$.bosdyn.api.ClearServiceFaultRequest\x1a%.bosdyn.api.ClearServiceFaultResponse\"\x00\x42\x13\x42\x11\x46\x61ultServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.fault_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\021FaultServiceProto'
  _globals['_FAULTSERVICE']._serialized_start=79
  _globals['_FAULTSERVICE']._serialized_end=299
# @@protoc_insertion_point(module_scope)
