# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/gripper_camera_param_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/gripper_camera_param_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import gripper_camera_param_pb2 as bosdyn_dot_api_dot_gripper__camera__param__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n-bosdyn/api/gripper_camera_param_service.proto\x12\nbosdyn.api\x1a%bosdyn/api/gripper_camera_param.proto2\xdd\x01\n\x19GripperCameraParamService\x12\\\n\tSetParams\x12%.bosdyn.api.GripperCameraParamRequest\x1a&.bosdyn.api.GripperCameraParamResponse\"\x00\x12\x62\n\tGetParams\x12(.bosdyn.api.GripperCameraGetParamRequest\x1a).bosdyn.api.GripperCameraGetParamResponse\"\x00\x42 B\x1eGripperCameraParamServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.gripper_camera_param_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\036GripperCameraParamServiceProto'
  _globals['_GRIPPERCAMERAPARAMSERVICE']._serialized_start=101
  _globals['_GRIPPERCAMERAPARAMSERVICE']._serialized_end=322
# @@protoc_insertion_point(module_scope)
