# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/image_geometry.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/image_geometry.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x62osdyn/api/image_geometry.proto\x12\nbosdyn.api\"V\n\nRectangleI\x12\t\n\x01x\x18\x05 \x01(\x05\x12\t\n\x01y\x18\x06 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x07 \x01(\x05\x12\x0c\n\x04rows\x18\x08 \x01(\x05J\x04\x08\x01\x10\x02J\x04\x08\x02\x10\x03J\x04\x08\x03\x10\x04J\x04\x08\x04\x10\x05\"@\n\x05\x41reaI\x12+\n\trectangle\x18\x01 \x01(\x0b\x32\x16.bosdyn.api.RectangleIH\x00\x42\n\n\x08geometryB B\x12ImageGeometryProtoZ\nbosdyn/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.image_geometry_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\022ImageGeometryProtoZ\nbosdyn/api'
  _globals['_RECTANGLEI']._serialized_start=47
  _globals['_RECTANGLEI']._serialized_end=133
  _globals['_AREAI']._serialized_start=135
  _globals['_AREAI']._serialized_end=199
# @@protoc_insertion_point(module_scope)
