# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/local_grid_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/local_grid_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import local_grid_pb2 as bosdyn_dot_api_dot_local__grid__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#bosdyn/api/local_grid_service.proto\x12\nbosdyn.api\x1a\x1b\x62osdyn/api/local_grid.proto2\xce\x01\n\x10LocalGridService\x12\x62\n\x11GetLocalGridTypes\x12$.bosdyn.api.GetLocalGridTypesRequest\x1a%.bosdyn.api.GetLocalGridTypesResponse\"\x00\x12V\n\rGetLocalGrids\x12 .bosdyn.api.GetLocalGridsRequest\x1a!.bosdyn.api.GetLocalGridsResponse\"\x00\x42\x17\x42\x15LocalGridServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.local_grid_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\025LocalGridServiceProto'
  _globals['_LOCALGRIDSERVICE']._serialized_start=81
  _globals['_LOCALGRIDSERVICE']._serialized_end=287
# @@protoc_insertion_point(module_scope)
