# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/manipulation_api_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/manipulation_api_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import manipulation_api_pb2 as bosdyn_dot_api_dot_manipulation__api__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)bosdyn/api/manipulation_api_service.proto\x12\nbosdyn.api\x1a!bosdyn/api/manipulation_api.proto2\xca\x02\n\x16ManipulationApiService\x12\\\n\x0fManipulationApi\x12\".bosdyn.api.ManipulationApiRequest\x1a#.bosdyn.api.ManipulationApiResponse\"\x00\x12t\n\x17ManipulationApiFeedback\x12*.bosdyn.api.ManipulationApiFeedbackRequest\x1a+.bosdyn.api.ManipulationApiFeedbackResponse\"\x00\x12\\\n\rOverrideGrasp\x12#.bosdyn.api.ApiGraspOverrideRequest\x1a$.bosdyn.api.ApiGraspOverrideResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.manipulation_api_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MANIPULATIONAPISERVICE']._serialized_start=93
  _globals['_MANIPULATIONAPISERVICE']._serialized_end=423
# @@protoc_insertion_point(module_scope)
