# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/ray_cast.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/ray_cast.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import header_pb2 as bosdyn_dot_api_dot_header__pb2
from bosdyn.api import geometry_pb2 as bosdyn_dot_api_dot_geometry__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x62osdyn/api/ray_cast.proto\x12\nbosdyn.api\x1a\x17\x62osdyn/api/header.proto\x1a\x19\x62osdyn/api/geometry.proto\"\xd2\x01\n\x0eRaycastRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12\x16\n\x0eray_frame_name\x18\x05 \x01(\t\x12\x1c\n\x03ray\x18\x02 \x01(\x0b\x32\x0f.bosdyn.api.Ray\x12!\n\x19min_intersection_distance\x18\x04 \x01(\x02\x12<\n\x12intersection_types\x18\x07 \x03(\x0e\x32 .bosdyn.api.RayIntersection.Type\"\xff\x01\n\x0fRayIntersection\x12.\n\x04type\x18\x01 \x01(\x0e\x32 .bosdyn.api.RayIntersection.Type\x12\x33\n\x19hit_position_in_hit_frame\x18\x02 \x01(\x0b\x32\x10.bosdyn.api.Vec3\x12\x17\n\x0f\x64istance_meters\x18\x03 \x01(\x01\"n\n\x04Type\x12\x10\n\x0cTYPE_UNKNOWN\x10\x00\x12\x15\n\x11TYPE_GROUND_PLANE\x10\x01\x12\x14\n\x10TYPE_TERRAIN_MAP\x10\x02\x12\x12\n\x0eTYPE_VOXEL_MAP\x10\x03\x12\x13\n\x0fTYPE_HAND_DEPTH\x10\x04\"\x8b\x03\n\x0fRaycastResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12\x32\n\x06status\x18\x05 \x01(\x0e\x32\".bosdyn.api.RaycastResponse.Status\x12\x0f\n\x07message\x18\x06 \x01(\t\x12\x16\n\x0ehit_frame_name\x18\x03 \x01(\t\x12)\n\x04hits\x18\x02 \x03(\x0b\x32\x1b.bosdyn.api.RayIntersection\x12:\n\x13transforms_snapshot\x18\x04 \x01(\x0b\x32\x1d.bosdyn.api.FrameTreeSnapshot\"\x87\x01\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x1a\n\x16STATUS_INVALID_REQUEST\x10\x02\x12$\n STATUS_INVALID_INTERSECTION_TYPE\x10\x03\x12\x18\n\x14STATUS_UNKNOWN_FRAME\x10\x04\x42\x0e\x42\x0cRayCastProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.ray_cast_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\014RayCastProto'
  _globals['_RAYCASTREQUEST']._serialized_start=94
  _globals['_RAYCASTREQUEST']._serialized_end=304
  _globals['_RAYINTERSECTION']._serialized_start=307
  _globals['_RAYINTERSECTION']._serialized_end=562
  _globals['_RAYINTERSECTION_TYPE']._serialized_start=452
  _globals['_RAYINTERSECTION_TYPE']._serialized_end=562
  _globals['_RAYCASTRESPONSE']._serialized_start=565
  _globals['_RAYCASTRESPONSE']._serialized_end=960
  _globals['_RAYCASTRESPONSE_STATUS']._serialized_start=825
  _globals['_RAYCASTRESPONSE_STATUS']._serialized_end=960
# @@protoc_insertion_point(module_scope)
