# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/units.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/units.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x62osdyn/api/units.proto\x12\nbosdyn.api\"\x8d\x01\n\x05Units\x12\x0e\n\x04name\x18\x01 \x01(\tH\x00\x12+\n\x04temp\x18\x02 \x01(\x0e\x32\x1b.bosdyn.api.TemperatureEnumH\x00\x12)\n\x05press\x18\x03 \x01(\x0e\x32\x18.bosdyn.api.PressureEnumH\x00\x12\x13\n\x0bis_relative\x18\x04 \x01(\x08\x42\x07\n\x05units*w\n\x0fTemperatureEnum\x12\x17\n\x13TEMPERATURE_UNKNOWN\x10\x00\x12\x16\n\x12TEMPERATURE_KELVIN\x10\x01\x12\x17\n\x13TEMPERATURE_CELSIUS\x10\x02\x12\x1a\n\x16TEMPERATURE_FAHRENHEIT\x10\x03*Z\n\x0cPressureEnum\x12\x14\n\x10PRESSURE_UNKNOWN\x10\x00\x12\x10\n\x0cPRESSURE_PSI\x10\x01\x12\x10\n\x0cPRESSURE_KPA\x10\x02\x12\x10\n\x0cPRESSURE_BAR\x10\x03\x42\x18\x42\nUnitsProtoZ\nbosdyn/apib\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.units_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\nUnitsProtoZ\nbosdyn/api'
  _globals['_TEMPERATUREENUM']._serialized_start=182
  _globals['_TEMPERATUREENUM']._serialized_end=301
  _globals['_PRESSUREENUM']._serialized_start=303
  _globals['_PRESSUREENUM']._serialized_end=393
  _globals['_UNITS']._serialized_start=39
  _globals['_UNITS']._serialized_end=180
# @@protoc_insertion_point(module_scope)
