# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/keepalive/keepalive_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/keepalive/keepalive_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api.keepalive import keepalive_pb2 as bosdyn_dot_api_dot_keepalive_dot_keepalive__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,bosdyn/api/keepalive/keepalive_service.proto\x12\x14\x62osdyn.api.keepalive\x1a$bosdyn/api/keepalive/keepalive.proto2\xb5\x02\n\x10KeepaliveService\x12g\n\x0cModifyPolicy\x12).bosdyn.api.keepalive.ModifyPolicyRequest\x1a*.bosdyn.api.keepalive.ModifyPolicyResponse\"\x00\x12X\n\x07\x43heckIn\x12$.bosdyn.api.keepalive.CheckInRequest\x1a%.bosdyn.api.keepalive.CheckInResponse\"\x00\x12^\n\tGetStatus\x12&.bosdyn.api.keepalive.GetStatusRequest\x1a\'.bosdyn.api.keepalive.GetStatusResponse\"\x00\x42\x17\x42\x15KeepaliveServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.keepalive.keepalive_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\025KeepaliveServiceProto'
  _globals['_KEEPALIVESERVICE']._serialized_start=109
  _globals['_KEEPALIVESERVICE']._serialized_end=418
# @@protoc_insertion_point(module_scope)
