# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/auto_return/auto_return_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/auto_return/auto_return_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api.auto_return import auto_return_pb2 as bosdyn_dot_api_dot_auto__return_dot_auto__return__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0bosdyn/api/auto_return/auto_return_service.proto\x12\x16\x62osdyn.api.auto_return\x1a(bosdyn/api/auto_return/auto_return.proto2\xc2\x02\n\x11\x41utoReturnService\x12`\n\tConfigure\x12(.bosdyn.api.auto_return.ConfigureRequest\x1a).bosdyn.api.auto_return.ConfigureResponse\x12u\n\x10GetConfiguration\x12/.bosdyn.api.auto_return.GetConfigurationRequest\x1a\x30.bosdyn.api.auto_return.GetConfigurationResponse\x12T\n\x05Start\x12$.bosdyn.api.auto_return.StartRequest\x1a%.bosdyn.api.auto_return.StartResponseB\x18\x42\x16\x41utoReturnServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.auto_return.auto_return_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\026AutoReturnServiceProto'
  _globals['_AUTORETURNSERVICE']._serialized_start=119
  _globals['_AUTORETURNSERVICE']._serialized_end=441
# @@protoc_insertion_point(module_scope)
