# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/metrics_logging/absolute_metrics.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/metrics_logging/absolute_metrics.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import data_buffer_pb2 as bosdyn_dot_api_dot_data__buffer__pb2
from bosdyn.api import parameter_pb2 as bosdyn_dot_api_dot_parameter__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1bosdyn/api/metrics_logging/absolute_metrics.proto\x12\x1a\x62osdyn.api.metrics_logging\x1a\x1c\x62osdyn/api/data_buffer.proto\x1a\x1a\x62osdyn/api/parameter.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9c\x02\n\x17\x41\x62soluteMetricsSnapshot\x12\x33\n\x0ftimestamp_start\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x31\n\rtimestamp_end\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fsequence_number\x18\x03 \x01(\x05\x12\x1b\n\x13robot_serial_number\x18\x04 \x01(\t\x12\x15\n\rrobot_species\x18\x05 \x01(\t\x12)\n\nparameters\x18\x06 \x03(\x0b\x32\x15.bosdyn.api.Parameter\x12!\n\x06\x65vents\x18\x07 \x03(\x0b\x32\x11.bosdyn.api.EventB\x16\x42\x14\x41\x62soluteMetricsProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.metrics_logging.absolute_metrics_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\024AbsoluteMetricsProto'
  _globals['_ABSOLUTEMETRICSSNAPSHOT']._serialized_start=173
  _globals['_ABSOLUTEMETRICSSNAPSHOT']._serialized_end=457
# @@protoc_insertion_point(module_scope)
