# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/graph_nav/lost_detection.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/graph_nav/lost_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)bosdyn/api/graph_nav/lost_detection.proto\x12\x14\x62osdyn.api.graph_nav*\xd9\x01\n\x16LostDetectorStrictness\x12$\n LOST_DETECTOR_STRICTNESS_UNKNOWN\x10\x00\x12%\n!LOST_DETECTOR_STRICTNESS_DISABLED\x10\x01\x12\'\n#LOST_DETECTOR_STRICTNESS_PERMISSIVE\x10\x02\x12$\n LOST_DETECTOR_STRICTNESS_DEFAULT\x10\x03\x12#\n\x1fLOST_DETECTOR_STRICTNESS_STRICT\x10\x04\x42\x14\x42\x12LostDetectionProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.graph_nav.lost_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\022LostDetectionProto'
  _globals['_LOSTDETECTORSTRICTNESS']._serialized_start=68
  _globals['_LOSTDETECTORSTRICTNESS']._serialized_end=285
# @@protoc_insertion_point(module_scope)
