# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/graph_nav/map_processing_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/graph_nav/map_processing_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api.graph_nav import map_processing_pb2 as bosdyn_dot_api_dot_graph__nav_dot_map__processing__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n1bosdyn/api/graph_nav/map_processing_service.proto\x12\x14\x62osdyn.api.graph_nav\x1a)bosdyn/api/graph_nav/map_processing.proto2\x81\x02\n\x14MapProcessingService\x12r\n\x0fProcessTopology\x12,.bosdyn.api.graph_nav.ProcessTopologyRequest\x1a-.bosdyn.api.graph_nav.ProcessTopologyResponse\"\x00\x30\x01\x12u\n\x10ProcessAnchoring\x12-.bosdyn.api.graph_nav.ProcessAnchoringRequest\x1a..bosdyn.api.graph_nav.ProcessAnchoringResponse\"\x00\x30\x01\x42\x1b\x42\x19MapProcessingServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.graph_nav.map_processing_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\031MapProcessingServiceProto'
  _globals['_MAPPROCESSINGSERVICE']._serialized_start=119
  _globals['_MAPPROCESSINGSERVICE']._serialized_end=376
# @@protoc_insertion_point(module_scope)
