# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/graph_nav/recording_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/graph_nav/recording_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api.graph_nav import recording_pb2 as bosdyn_dot_api_dot_graph__nav_dot_recording__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n,bosdyn/api/graph_nav/recording_service.proto\x12\x14\x62osdyn.api.graph_nav\x1a$bosdyn/api/graph_nav/recording.proto2\xc4\x05\n\x18GraphNavRecordingService\x12m\n\x0eStartRecording\x12+.bosdyn.api.graph_nav.StartRecordingRequest\x1a,.bosdyn.api.graph_nav.StartRecordingResponse\"\x00\x12j\n\rStopRecording\x12*.bosdyn.api.graph_nav.StopRecordingRequest\x1a+.bosdyn.api.graph_nav.StopRecordingResponse\"\x00\x12m\n\x0e\x43reateWaypoint\x12+.bosdyn.api.graph_nav.CreateWaypointRequest\x1a,.bosdyn.api.graph_nav.CreateWaypointResponse\"\x00\x12\x88\x01\n\x17SetRecordingEnvironment\x12\x34.bosdyn.api.graph_nav.SetRecordingEnvironmentRequest\x1a\x35.bosdyn.api.graph_nav.SetRecordingEnvironmentResponse\"\x00\x12\x61\n\nCreateEdge\x12\'.bosdyn.api.graph_nav.CreateEdgeRequest\x1a(.bosdyn.api.graph_nav.CreateEdgeResponse\"\x00\x12p\n\x0fGetRecordStatus\x12,.bosdyn.api.graph_nav.GetRecordStatusRequest\x1a-.bosdyn.api.graph_nav.GetRecordStatusResponse\"\x00\x42\x17\x42\x15RecordingServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.graph_nav.recording_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\025RecordingServiceProto'
  _globals['_GRAPHNAVRECORDINGSERVICE']._serialized_start=109
  _globals['_GRAPHNAVRECORDINGSERVICE']._serialized_end=817
# @@protoc_insertion_point(module_scope)
