# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/spot/door_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/spot/door_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api.spot import door_pb2 as bosdyn_dot_api_dot_spot_dot_door__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"bosdyn/api/spot/door_service.proto\x12\x0f\x62osdyn.api.spot\x1a\x1a\x62osdyn/api/spot/door.proto2\xd9\x01\n\x0b\x44oorService\x12_\n\x08OpenDoor\x12\'.bosdyn.api.spot.OpenDoorCommandRequest\x1a(.bosdyn.api.spot.OpenDoorCommandResponse\"\x00\x12i\n\x10OpenDoorFeedback\x12(.bosdyn.api.spot.OpenDoorFeedbackRequest\x1a).bosdyn.api.spot.OpenDoorFeedbackResponse\"\x00\x42\x19\x42\x17\x44oorCommandServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.spot.door_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\027DoorCommandServiceProto'
  _globals['_DOORSERVICE']._serialized_start=84
  _globals['_DOORSERVICE']._serialized_end=301
# @@protoc_insertion_point(module_scope)
