# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/spot/inverse_kinematics_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/spot/inverse_kinematics_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api.spot import inverse_kinematics_pb2 as bosdyn_dot_api_dot_spot_dot_inverse__kinematics__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0bosdyn/api/spot/inverse_kinematics_service.proto\x12\x0f\x62osdyn.api.spot\x1a(bosdyn/api/spot/inverse_kinematics.proto2\x88\x01\n\x18InverseKinematicsService\x12l\n\x11InverseKinematics\x12).bosdyn.api.spot.InverseKinematicsRequest\x1a*.bosdyn.api.spot.InverseKinematicsResponse\"\x00\x42\x1f\x42\x1dInverseKinematicsServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.spot.inverse_kinematics_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\035InverseKinematicsServiceProto'
  _globals['_INVERSEKINEMATICSSERVICE']._serialized_start=112
  _globals['_INVERSEKINEMATICSSERVICE']._serialized_end=248
# @@protoc_insertion_point(module_scope)
