# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/spot/spot_constants.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/spot/spot_constants.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$bosdyn/api/spot/spot_constants.proto\x12\x0f\x62osdyn.api.spot*\xc8\x03\n\nJointIndex\x12\x15\n\x11JOINT_INDEX_FL_HX\x10\x00\x12\x15\n\x11JOINT_INDEX_FL_HY\x10\x01\x12\x15\n\x11JOINT_INDEX_FL_KN\x10\x02\x12\x15\n\x11JOINT_INDEX_FR_HX\x10\x03\x12\x15\n\x11JOINT_INDEX_FR_HY\x10\x04\x12\x15\n\x11JOINT_INDEX_FR_KN\x10\x05\x12\x15\n\x11JOINT_INDEX_HL_HX\x10\x06\x12\x15\n\x11JOINT_INDEX_HL_HY\x10\x07\x12\x15\n\x11JOINT_INDEX_HL_KN\x10\x08\x12\x15\n\x11JOINT_INDEX_HR_HX\x10\t\x12\x15\n\x11JOINT_INDEX_HR_HY\x10\n\x12\x15\n\x11JOINT_INDEX_HR_KN\x10\x0b\x12\x16\n\x12JOINT_INDEX_A0_SH0\x10\x0c\x12\x16\n\x12JOINT_INDEX_A0_SH1\x10\r\x12\x16\n\x12JOINT_INDEX_A0_EL0\x10\x0e\x12\x16\n\x12JOINT_INDEX_A0_EL1\x10\x0f\x12\x16\n\x12JOINT_INDEX_A0_WR0\x10\x10\x12\x16\n\x12JOINT_INDEX_A0_WR1\x10\x11\x12\x16\n\x12JOINT_INDEX_A0_F1X\x10\x12*R\n\x08LegIndex\x12\x10\n\x0cLEG_INDEX_FL\x10\x00\x12\x10\n\x0cLEG_INDEX_FR\x10\x01\x12\x10\n\x0cLEG_INDEX_HL\x10\x02\x12\x10\n\x0cLEG_INDEX_HR\x10\x03*%\n\x0bLegDofOrder\x12\x06\n\x02HX\x10\x00\x12\x06\n\x02HY\x10\x01\x12\x06\n\x02KN\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.spot.spot_constants_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_JOINTINDEX']._serialized_start=58
  _globals['_JOINTINDEX']._serialized_end=514
  _globals['_LEGINDEX']._serialized_start=516
  _globals['_LEGINDEX']._serialized_end=598
  _globals['_LEGDOFORDER']._serialized_start=600
  _globals['_LEGDOFORDER']._serialized_end=637
# @@protoc_insertion_point(module_scope)
