# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/alerts.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/alerts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x62osdyn/api/alerts.proto\x12\nbosdyn.api\x1a\x1cgoogle/protobuf/struct.proto\"\xaa\x02\n\tAlertData\x12\x35\n\x08severity\x18\x01 \x01(\x0e\x32#.bosdyn.api.AlertData.SeverityLevel\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x30\n\x0f\x61\x64\x64itional_data\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x94\x01\n\rSeverityLevel\x12\x1a\n\x16SEVERITY_LEVEL_UNKNOWN\x10\x00\x12\x17\n\x13SEVERITY_LEVEL_INFO\x10\x01\x12\x17\n\x13SEVERITY_LEVEL_WARN\x10\x02\x12\x18\n\x14SEVERITY_LEVEL_ERROR\x10\x03\x12\x1b\n\x17SEVERITY_LEVEL_CRITICAL\x10\x04\x42\rB\x0b\x41lertsProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.alerts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\013AlertsProto'
  _globals['_ALERTDATA']._serialized_start=70
  _globals['_ALERTDATA']._serialized_end=368
  _globals['_ALERTDATA_SEVERITYLEVEL']._serialized_start=220
  _globals['_ALERTDATA_SEVERITYLEVEL']._serialized_end=368
# @@protoc_insertion_point(module_scope)
