# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/data_acquisition_plugin_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/data_acquisition_plugin_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import data_acquisition_pb2 as bosdyn_dot_api_dot_data__acquisition__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n0bosdyn/api/data_acquisition_plugin_service.proto\x12\nbosdyn.api\x1a!bosdyn/api/data_acquisition.proto2\xcf\x03\n\x1c\x44\x61taAcquisitionPluginService\x12`\n\x11\x41\x63quirePluginData\x12$.bosdyn.api.AcquirePluginDataRequest\x1a%.bosdyn.api.AcquirePluginDataResponse\x12H\n\tGetStatus\x12\x1c.bosdyn.api.GetStatusRequest\x1a\x1d.bosdyn.api.GetStatusResponse\x12W\n\x0eGetServiceInfo\x12!.bosdyn.api.GetServiceInfoRequest\x1a\".bosdyn.api.GetServiceInfoResponse\x12`\n\x11\x43\x61ncelAcquisition\x12$.bosdyn.api.CancelAcquisitionRequest\x1a%.bosdyn.api.CancelAcquisitionResponse\x12H\n\x0bGetLiveData\x12\x1b.bosdyn.api.LiveDataRequest\x1a\x1c.bosdyn.api.LiveDataResponseB#B!DataAcquisitionPluginServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.data_acquisition_plugin_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B!DataAcquisitionPluginServiceProto'
  _globals['_DATAACQUISITIONPLUGINSERVICE']._serialized_start=100
  _globals['_DATAACQUISITIONPLUGINSERVICE']._serialized_end=563
# @@protoc_insertion_point(module_scope)
