# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/data_acquisition_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/data_acquisition_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import data_acquisition_pb2 as bosdyn_dot_api_dot_data__acquisition__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n)bosdyn/api/data_acquisition_service.proto\x12\nbosdyn.api\x1a!bosdyn/api/data_acquisition.proto2\xb7\x03\n\x16\x44\x61taAcquisitionService\x12N\n\x0b\x41\x63quireData\x12\x1e.bosdyn.api.AcquireDataRequest\x1a\x1f.bosdyn.api.AcquireDataResponse\x12H\n\tGetStatus\x12\x1c.bosdyn.api.GetStatusRequest\x1a\x1d.bosdyn.api.GetStatusResponse\x12W\n\x0eGetServiceInfo\x12!.bosdyn.api.GetServiceInfoRequest\x1a\".bosdyn.api.GetServiceInfoResponse\x12`\n\x11\x43\x61ncelAcquisition\x12$.bosdyn.api.CancelAcquisitionRequest\x1a%.bosdyn.api.CancelAcquisitionResponse\x12H\n\x0bGetLiveData\x12\x1b.bosdyn.api.LiveDataRequest\x1a\x1c.bosdyn.api.LiveDataResponseB\x1d\x42\x1b\x44\x61taAcquisitionServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.data_acquisition_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\033DataAcquisitionServiceProto'
  _globals['_DATAACQUISITIONSERVICE']._serialized_start=93
  _globals['_DATAACQUISITIONSERVICE']._serialized_end=532
# @@protoc_insertion_point(module_scope)
