# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/directory_registration.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/directory_registration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import directory_pb2 as bosdyn_dot_api_dot_directory__pb2
from bosdyn.api import header_pb2 as bosdyn_dot_api_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'bosdyn/api/directory_registration.proto\x12\nbosdyn.api\x1a\x1a\x62osdyn/api/directory.proto\x1a\x17\x62osdyn/api/header.proto\"\x9c\x01\n\x16RegisterServiceRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12&\n\x08\x65ndpoint\x18\x02 \x01(\x0b\x32\x14.bosdyn.api.Endpoint\x12/\n\rservice_entry\x18\x03 \x01(\x0b\x32\x18.bosdyn.api.ServiceEntry\"\xc9\x01\n\x17RegisterServiceResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12:\n\x06status\x18\x02 \x01(\x0e\x32*.bosdyn.api.RegisterServiceResponse.Status\"F\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x19\n\x15STATUS_ALREADY_EXISTS\x10\x02\"[\n\x18UnregisterServiceRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\"\xd2\x01\n\x19UnregisterServiceResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12<\n\x06status\x18\x02 \x01(\x0e\x32,.bosdyn.api.UnregisterServiceResponse.Status\"K\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x1e\n\x1aSTATUS_NONEXISTENT_SERVICE\x10\x02\"\x9a\x01\n\x14UpdateServiceRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12&\n\x08\x65ndpoint\x18\x02 \x01(\x0b\x32\x14.bosdyn.api.Endpoint\x12/\n\rservice_entry\x18\x03 \x01(\x0b\x32\x18.bosdyn.api.ServiceEntry\"\xca\x01\n\x15UpdateServiceResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12\x38\n\x06status\x18\x02 \x01(\x0e\x32(.bosdyn.api.UpdateServiceResponse.Status\"K\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\r\n\tSTATUS_OK\x10\x01\x12\x1e\n\x1aSTATUS_NONEXISTENT_SERVICE\x10\x02\x42\x1c\x42\x1a\x44irectoryRegistrationProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.directory_registration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\032DirectoryRegistrationProto'
  _globals['_REGISTERSERVICEREQUEST']._serialized_start=109
  _globals['_REGISTERSERVICEREQUEST']._serialized_end=265
  _globals['_REGISTERSERVICERESPONSE']._serialized_start=268
  _globals['_REGISTERSERVICERESPONSE']._serialized_end=469
  _globals['_REGISTERSERVICERESPONSE_STATUS']._serialized_start=399
  _globals['_REGISTERSERVICERESPONSE_STATUS']._serialized_end=469
  _globals['_UNREGISTERSERVICEREQUEST']._serialized_start=471
  _globals['_UNREGISTERSERVICEREQUEST']._serialized_end=562
  _globals['_UNREGISTERSERVICERESPONSE']._serialized_start=565
  _globals['_UNREGISTERSERVICERESPONSE']._serialized_end=775
  _globals['_UNREGISTERSERVICERESPONSE_STATUS']._serialized_start=700
  _globals['_UNREGISTERSERVICERESPONSE_STATUS']._serialized_end=775
  _globals['_UPDATESERVICEREQUEST']._serialized_start=778
  _globals['_UPDATESERVICEREQUEST']._serialized_end=932
  _globals['_UPDATESERVICERESPONSE']._serialized_start=935
  _globals['_UPDATESERVICERESPONSE']._serialized_end=1137
  _globals['_UPDATESERVICERESPONSE_STATUS']._serialized_start=700
  _globals['_UPDATESERVICERESPONSE_STATUS']._serialized_end=775
# @@protoc_insertion_point(module_scope)
