# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/ir_enable_disable.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/ir_enable_disable.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import header_pb2 as bosdyn_dot_api_dot_header__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"bosdyn/api/ir_enable_disable.proto\x12\nbosdyn.api\x1a\x17\x62osdyn/api/header.proto\"\xc1\x01\n\x16IREnableDisableRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12;\n\x07request\x18\x02 \x01(\x0e\x32*.bosdyn.api.IREnableDisableRequest.Request\"?\n\x07Request\x12\x13\n\x0fREQUEST_UNKNOWN\x10\x00\x12\x0f\n\x0bREQUEST_OFF\x10\x01\x12\x0e\n\nREQUEST_ON\x10\x02\"E\n\x17IREnableDisableResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeaderB\x16\x42\x14IREnableDisableProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.ir_enable_disable_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\024IREnableDisableProto'
  _globals['_IRENABLEDISABLEREQUEST']._serialized_start=76
  _globals['_IRENABLEDISABLEREQUEST']._serialized_end=269
  _globals['_IRENABLEDISABLEREQUEST_REQUEST']._serialized_start=206
  _globals['_IRENABLEDISABLEREQUEST_REQUEST']._serialized_end=269
  _globals['_IRENABLEDISABLERESPONSE']._serialized_start=271
  _globals['_IRENABLEDISABLERESPONSE']._serialized_end=340
# @@protoc_insertion_point(module_scope)
