# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/ir_enable_disable_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/ir_enable_disable_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import ir_enable_disable_pb2 as bosdyn_dot_api_dot_ir__enable__disable__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*bosdyn/api/ir_enable_disable_service.proto\x12\nbosdyn.api\x1a\"bosdyn/api/ir_enable_disable.proto2v\n\x16IREnableDisableService\x12\\\n\x0fIREnableDisable\x12\".bosdyn.api.IREnableDisableRequest\x1a#.bosdyn.api.IREnableDisableResponse\"\x00\x42\x1d\x42\x1bIREnableDisableServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.ir_enable_disable_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\033IREnableDisableServiceProto'
  _globals['_IRENABLEDISABLESERVICE']._serialized_start=94
  _globals['_IRENABLEDISABLESERVICE']._serialized_end=212
# @@protoc_insertion_point(module_scope)
