# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/lease_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/lease_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import lease_pb2 as bosdyn_dot_api_dot_lease__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62osdyn/api/lease_service.proto\x12\nbosdyn.api\x1a\x16\x62osdyn/api/lease.proto2\x98\x03\n\x0cLeaseService\x12Q\n\x0c\x41\x63quireLease\x12\x1f.bosdyn.api.AcquireLeaseRequest\x1a .bosdyn.api.AcquireLeaseResponse\x12H\n\tTakeLease\x12\x1c.bosdyn.api.TakeLeaseRequest\x1a\x1d.bosdyn.api.TakeLeaseResponse\x12N\n\x0bReturnLease\x12\x1e.bosdyn.api.ReturnLeaseRequest\x1a\x1f.bosdyn.api.ReturnLeaseResponse\x12K\n\nListLeases\x12\x1d.bosdyn.api.ListLeasesRequest\x1a\x1e.bosdyn.api.ListLeasesResponse\x12N\n\x0bRetainLease\x12\x1e.bosdyn.api.RetainLeaseRequest\x1a\x1f.bosdyn.api.RetainLeaseResponseB\x13\x42\x11LeaseServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.lease_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\021LeaseServiceProto'
  _globals['_LEASESERVICE']._serialized_start=71
  _globals['_LEASESERVICE']._serialized_end=479
# @@protoc_insertion_point(module_scope)
