# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/license.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/license.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import header_pb2 as bosdyn_dot_api_dot_header__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x62osdyn/api/license.proto\x12\nbosdyn.api\x1a\x17\x62osdyn/api/header.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8d\x03\n\x0bLicenseInfo\x12.\n\x06status\x18\x01 \x01(\x0e\x32\x1e.bosdyn.api.LicenseInfo.Status\x12\n\n\x02id\x18\x02 \x01(\t\x12\x14\n\x0crobot_serial\x18\x03 \x01(\t\x12\x34\n\x10not_valid_before\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\x0fnot_valid_after\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x11licensed_features\x18\x06 \x03(\t\"\xa5\x01\n\x06Status\x12\x12\n\x0eSTATUS_UNKNOWN\x10\x00\x12\x10\n\x0cSTATUS_VALID\x10\x01\x12\x12\n\x0eSTATUS_EXPIRED\x10\x02\x12\x18\n\x14STATUS_NOT_YET_VALID\x10\x03\x12\x14\n\x10STATUS_MALFORMED\x10\x04\x12\x1a\n\x16STATUS_SERIAL_MISMATCH\x10\x05\x12\x15\n\x11STATUS_NO_LICENSE\x10\x06\"B\n\x15GetLicenseInfoRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\"n\n\x16GetLicenseInfoResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12(\n\x07license\x18\x02 \x01(\x0b\x32\x17.bosdyn.api.LicenseInfo\"\\\n\x18GetFeatureEnabledRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12\x15\n\rfeature_codes\x18\x02 \x03(\t\"\xd2\x01\n\x19GetFeatureEnabledResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12R\n\x0f\x66\x65\x61ture_enabled\x18\x02 \x03(\x0b\x32\x39.bosdyn.api.GetFeatureEnabledResponse.FeatureEnabledEntry\x1a\x35\n\x13\x46\x65\x61tureEnabledEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x08:\x02\x38\x01\x42\x0e\x42\x0cLicenseProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.license_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\014LicenseProto'
  _globals['_GETFEATUREENABLEDRESPONSE_FEATUREENABLEDENTRY']._loaded_options = None
  _globals['_GETFEATUREENABLEDRESPONSE_FEATUREENABLEDENTRY']._serialized_options = b'8\001'
  _globals['_LICENSEINFO']._serialized_start=99
  _globals['_LICENSEINFO']._serialized_end=496
  _globals['_LICENSEINFO_STATUS']._serialized_start=331
  _globals['_LICENSEINFO_STATUS']._serialized_end=496
  _globals['_GETLICENSEINFOREQUEST']._serialized_start=498
  _globals['_GETLICENSEINFOREQUEST']._serialized_end=564
  _globals['_GETLICENSEINFORESPONSE']._serialized_start=566
  _globals['_GETLICENSEINFORESPONSE']._serialized_end=676
  _globals['_GETFEATUREENABLEDREQUEST']._serialized_start=678
  _globals['_GETFEATUREENABLEDREQUEST']._serialized_end=770
  _globals['_GETFEATUREENABLEDRESPONSE']._serialized_start=773
  _globals['_GETFEATUREENABLEDRESPONSE']._serialized_end=983
  _globals['_GETFEATUREENABLEDRESPONSE_FEATUREENABLEDENTRY']._serialized_start=930
  _globals['_GETFEATUREENABLEDRESPONSE_FEATUREENABLEDENTRY']._serialized_end=983
# @@protoc_insertion_point(module_scope)
