# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/network_compute_bridge_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/network_compute_bridge_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import network_compute_bridge_pb2 as bosdyn_dot_api_dot_network__compute__bridge__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n/bosdyn/api/network_compute_bridge_service.proto\x12\nbosdyn.api\x1a\'bosdyn/api/network_compute_bridge.proto2\xdb\x01\n\x14NetworkComputeBridge\x12Y\n\x0eNetworkCompute\x12!.bosdyn.api.NetworkComputeRequest\x1a\".bosdyn.api.NetworkComputeResponse\"\x00\x12h\n\x13ListAvailableModels\x12&.bosdyn.api.ListAvailableModelsRequest\x1a\'.bosdyn.api.ListAvailableModelsResponse\"\x00\x32\xbc\x02\n\x1aNetworkComputeBridgeWorker\x12\\\n\x0eNetworkCompute\x12!.bosdyn.api.NetworkComputeRequest\x1a\".bosdyn.api.NetworkComputeResponse\"\x03\x88\x02\x01\x12V\n\rWorkerCompute\x12 .bosdyn.api.WorkerComputeRequest\x1a!.bosdyn.api.WorkerComputeResponse\"\x00\x12h\n\x13ListAvailableModels\x12&.bosdyn.api.ListAvailableModelsRequest\x1a\'.bosdyn.api.ListAvailableModelsResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.network_compute_bridge_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NETWORKCOMPUTEBRIDGEWORKER'].methods_by_name['NetworkCompute']._loaded_options = None
  _globals['_NETWORKCOMPUTEBRIDGEWORKER'].methods_by_name['NetworkCompute']._serialized_options = b'\210\002\001'
  _globals['_NETWORKCOMPUTEBRIDGE']._serialized_start=105
  _globals['_NETWORKCOMPUTEBRIDGE']._serialized_end=324
  _globals['_NETWORKCOMPUTEBRIDGEWORKER']._serialized_start=327
  _globals['_NETWORKCOMPUTEBRIDGEWORKER']._serialized_end=643
# @@protoc_insertion_point(module_scope)
