# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/point_cloud_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/point_cloud_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import point_cloud_pb2 as bosdyn_dot_api_dot_point__cloud__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$bosdyn/api/point_cloud_service.proto\x12\nbosdyn.api\x1a\x1c\x62osdyn/api/point_cloud.proto2\xdb\x01\n\x11PointCloudService\x12n\n\x15ListPointCloudSources\x12(.bosdyn.api.ListPointCloudSourcesRequest\x1a).bosdyn.api.ListPointCloudSourcesResponse\"\x00\x12V\n\rGetPointCloud\x12 .bosdyn.api.GetPointCloudRequest\x1a!.bosdyn.api.GetPointCloudResponse\"\x00\x42\x18\x42\x16PointCloudServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.point_cloud_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\026PointCloudServiceProto'
  _globals['_POINTCLOUDSERVICE']._serialized_start=83
  _globals['_POINTCLOUDSERVICE']._serialized_end=302
# @@protoc_insertion_point(module_scope)
