# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/power_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/power_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import power_pb2 as bosdyn_dot_api_dot_power__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1e\x62osdyn/api/power_service.proto\x12\nbosdyn.api\x1a\x16\x62osdyn/api/power.proto2\x82\x04\n\x0cPowerService\x12S\n\x0cPowerCommand\x12\x1f.bosdyn.api.PowerCommandRequest\x1a .bosdyn.api.PowerCommandResponse\"\x00\x12k\n\x14PowerCommandFeedback\x12\'.bosdyn.api.PowerCommandFeedbackRequest\x1a(.bosdyn.api.PowerCommandFeedbackResponse\"\x00\x12\\\n\x0f\x46\x61nPowerCommand\x12\".bosdyn.api.FanPowerCommandRequest\x1a#.bosdyn.api.FanPowerCommandResponse\"\x00\x12t\n\x17\x46\x61nPowerCommandFeedback\x12*.bosdyn.api.FanPowerCommandFeedbackRequest\x1a+.bosdyn.api.FanPowerCommandFeedbackResponse\"\x00\x12\\\n\x0fResetSafetyStop\x12\".bosdyn.api.ResetSafetyStopRequest\x1a#.bosdyn.api.ResetSafetyStopResponse\"\x00\x42\x13\x42\x11PowerServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.power_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\021PowerServiceProto'
  _globals['_POWERSERVICE']._serialized_start=71
  _globals['_POWERSERVICE']._serialized_end=585
# @@protoc_insertion_point(module_scope)
