# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/signals.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/signals.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import geometry_pb2 as bosdyn_dot_api_dot_geometry__pb2
from bosdyn.api import alerts_pb2 as bosdyn_dot_api_dot_alerts__pb2
from bosdyn.api import units_pb2 as bosdyn_dot_api_dot_units__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18\x62osdyn/api/signals.proto\x12\nbosdyn.api\x1a\x19\x62osdyn/api/geometry.proto\x1a\x17\x62osdyn/api/alerts.proto\x1a\x16\x62osdyn/api/units.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/wrappers.proto\"E\n\x11SignalDisplayInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\r\n\x05order\x18\x03 \x01(\x03\"\xbd\x01\n\x10SensorOutputSpec\x12\"\n\x06\x62ounds\x18\x01 \x01(\x0b\x32\x12.bosdyn.api.Bounds\x12\x30\n\nresolution\x18\x02 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\x12 \n\x05units\x18\x03 \x01(\x0b\x32\x11.bosdyn.api.Units\x12\x31\n\x0bsample_rate\x18\x04 \x01(\x0b\x32\x1c.google.protobuf.DoubleValue\"\xa0\x01\n\x12\x41lertConditionSpec\x12)\n\nalert_data\x18\x01 \x01(\x0b\x32\x15.bosdyn.api.AlertData\x12\r\n\x03min\x18\x02 \x01(\x01H\x00\x12\r\n\x03max\x18\x03 \x01(\x01H\x00\x12$\n\x06\x62ounds\x18\x04 \x01(\x0b\x32\x12.bosdyn.api.BoundsH\x00\x12\x13\n\tcondition\x18\x05 \x01(\x08H\x00\x42\x06\n\x04type\"\x97\x01\n\nSignalSpec\x12+\n\x04info\x18\x01 \x01(\x0b\x32\x1d.bosdyn.api.SignalDisplayInfo\x12,\n\x06sensor\x18\x02 \x01(\x0b\x32\x1c.bosdyn.api.SensorOutputSpec\x12.\n\x06\x61lerts\x18\x03 \x03(\x0b\x32\x1e.bosdyn.api.AlertConditionSpec\"\xba\x01\n\nSignalData\x12)\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\x1b.bosdyn.api.SignalData.Data\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x1aR\n\x04\x44\x61ta\x12\x10\n\x06\x64ouble\x18\x01 \x01(\x01H\x00\x12\r\n\x03int\x18\x02 \x01(\x03H\x00\x12\x10\n\x06string\x18\x03 \x01(\tH\x00\x12\x0e\n\x04\x62ool\x18\x04 \x01(\x08H\x00\x42\x07\n\x05value\"b\n\x06Signal\x12+\n\x0bsignal_spec\x18\x01 \x01(\x0b\x32\x16.bosdyn.api.SignalSpec\x12+\n\x0bsignal_data\x18\x02 \x01(\x0b\x32\x16.bosdyn.api.SignalDataB\x0e\x42\x0cSignalsProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.signals_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\014SignalsProto'
  _globals['_SIGNALDISPLAYINFO']._serialized_start=181
  _globals['_SIGNALDISPLAYINFO']._serialized_end=250
  _globals['_SENSOROUTPUTSPEC']._serialized_start=253
  _globals['_SENSOROUTPUTSPEC']._serialized_end=442
  _globals['_ALERTCONDITIONSPEC']._serialized_start=445
  _globals['_ALERTCONDITIONSPEC']._serialized_end=605
  _globals['_SIGNALSPEC']._serialized_start=608
  _globals['_SIGNALSPEC']._serialized_end=759
  _globals['_SIGNALDATA']._serialized_start=762
  _globals['_SIGNALDATA']._serialized_end=948
  _globals['_SIGNALDATA_DATA']._serialized_start=866
  _globals['_SIGNALDATA_DATA']._serialized_end=948
  _globals['_SIGNAL']._serialized_start=950
  _globals['_SIGNAL']._serialized_end=1048
# @@protoc_insertion_point(module_scope)
