# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/time_sync_service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/time_sync_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import time_sync_pb2 as bosdyn_dot_api_dot_time__sync__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"bosdyn/api/time_sync_service.proto\x12\nbosdyn.api\x1a\x1a\x62osdyn/api/time_sync.proto2l\n\x0fTimeSyncService\x12Y\n\x0eTimeSyncUpdate\x12!.bosdyn.api.TimeSyncUpdateRequest\x1a\".bosdyn.api.TimeSyncUpdateResponse\"\x00\x42\x16\x42\x14TimeSyncServiceProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.time_sync_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\024TimeSyncServiceProto'
  _globals['_TIMESYNCSERVICE']._serialized_start=78
  _globals['_TIMESYNCSERVICE']._serialized_end=186
# @@protoc_insertion_point(module_scope)
