# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bosdyn/api/metrics_logging/metrics_logging_robot.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'bosdyn/api/metrics_logging/metrics_logging_robot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from bosdyn.api import data_buffer_pb2 as bosdyn_dot_api_dot_data__buffer__pb2
from bosdyn.api import header_pb2 as bosdyn_dot_api_dot_header__pb2
from bosdyn.api import parameter_pb2 as bosdyn_dot_api_dot_parameter__pb2
from bosdyn.api.metrics_logging import signed_proto_pb2 as bosdyn_dot_api_dot_metrics__logging_dot_signed__proto__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n6bosdyn/api/metrics_logging/metrics_logging_robot.proto\x12\x1a\x62osdyn.api.metrics_logging\x1a\x1c\x62osdyn/api/data_buffer.proto\x1a\x17\x62osdyn/api/header.proto\x1a\x1a\x62osdyn/api/parameter.proto\x1a-bosdyn/api/metrics_logging/signed_proto.proto\"I\n\x1cGetStoreSequenceRangeRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\"\x88\x01\n\x1dGetStoreSequenceRangeResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12\x1d\n\x15\x66irst_sequence_number\x18\x02 \x01(\x05\x12\x1c\n\x14last_sequence_number\x18\x03 \x01(\x05\"g\n GetAbsoluteMetricSnapshotRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12\x18\n\x10sequence_numbers\x18\x02 \x03(\x05\"\x8b\x01\n!GetAbsoluteMetricSnapshotResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12:\n\tsnapshots\x18\x02 \x03(\x0b\x32\'.bosdyn.api.metrics_logging.SignedProto\"d\n\x11GetMetricsRequest\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.bosdyn.api.RequestHeader\x12\x0c\n\x04keys\x18\x02 \x03(\t\x12\x16\n\x0einclude_events\x18\x03 \x01(\x08\"\xa4\x01\n\x12GetMetricsResponse\x12*\n\x06header\x18\x01 \x01(\x0b\x32\x1a.bosdyn.api.ResponseHeader\x12)\n\nparameters\x18\x02 \x03(\x0b\x32\x15.bosdyn.api.Parameter\x12\x14\n\x0cmissing_keys\x18\x03 \x03(\t\x12!\n\x06\x65vents\x18\x04 \x03(\x0b\x32\x11.bosdyn.api.EventB\x1a\x42\x18MetricsLoggingRobotProtob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bosdyn.api.metrics_logging.metrics_logging_robot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'B\030MetricsLoggingRobotProto'
  _globals['_GETSTORESEQUENCERANGEREQUEST']._serialized_start=216
  _globals['_GETSTORESEQUENCERANGEREQUEST']._serialized_end=289
  _globals['_GETSTORESEQUENCERANGERESPONSE']._serialized_start=292
  _globals['_GETSTORESEQUENCERANGERESPONSE']._serialized_end=428
  _globals['_GETABSOLUTEMETRICSNAPSHOTREQUEST']._serialized_start=430
  _globals['_GETABSOLUTEMETRICSNAPSHOTREQUEST']._serialized_end=533
  _globals['_GETABSOLUTEMETRICSNAPSHOTRESPONSE']._serialized_start=536
  _globals['_GETABSOLUTEMETRICSNAPSHOTRESPONSE']._serialized_end=675
  _globals['_GETMETRICSREQUEST']._serialized_start=677
  _globals['_GETMETRICSREQUEST']._serialized_end=777
  _globals['_GETMETRICSRESPONSE']._serialized_start=780
  _globals['_GETMETRICSRESPONSE']._serialized_end=944
# @@protoc_insertion_point(module_scope)
